services:
  api: 
      image: ghcr.io/sonnyad/utile-api:main
      build: utile-api/.
      ports: 
        - "3000:3000"
      env_file: 
        - ./.env
      restart: always
      pull_policy: always
  bot:
      build: utile-bot/.
      env_file:
        - ./.env
      environment:
        - NOSTR_PRIVKEY=$NOSTR_PRIVKEY
      restart: always
  front:
      image: ghcr.io/sonnyad/utile-front:main
      build: utile-front/.
      ports: 
        - "2000:2000"
      env_file:
        - ./.env
      restart: always
      pull_policy: always
  spectrum-frontend:
      image: ghcr.io/opinions-sur-rue/spectrum-frontend:latest
      ports: 
        - "2001:2000"
      env_file:
        - ./.env
      restart: always
      pull_policy: always
  spectrum-backend:
      image: ghcr.io/opinions-sur-rue/spectrum-backend:latest
      ports: 
        - "3001:3000"
      env_file:
        - ./.env
      restart: always
      pull_policy: always
