version: "3.9"
services:
  api: 
      build: utile-api/.
      ports: 
        - "3000:3000"
      env_file: 
        - ./.env
      restart: always
  bot:
      build: utile-bot/.
      env_file:
        - ./.env
      environment:
        - NOSTR_PRIVKEY=$NOSTR_PRIVKEY
      restart: always
  front: 
      build: utile-front/.
      ports: 
        - "2000:2000"
      restart: always
      env_file:
        - ./.env      
