version: "3.9"
services:
  docs:
      build: utile-api-docs/.
      ports: 
        - "8000:8080"
      restart: always
  api: 
      build: utile-api/.
      ports: 
        - "3000:3000"
      env_file: 
        - utile-api/.env
      restart: always
  bot:
      build: utile-bot/.
      env_file:
        - utile-bot/.env
      restart: always
  front: 
      build: utile-front/.
      ports: 
        - "2000:2000"
      restart: always
